[features]
seeds = true
skip-lint = false
[programs.devnet]
anchor_grizzly = "4m2iCzvckHmiXf4bV4xHckVAE2tMNLt2GgUziSr7uTiF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"